[2025-01-07T13:02:22.828+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:22.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-01-07T13:02:22.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-01-07T13:02:22.883+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-01-07T13:02:22.951+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2024-12-28 00:00:00+00:00
[2025-01-07T13:02:22.962+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1351) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:22.964+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmp4jrptza4']
[2025-01-07T13:02:22.965+0000] {standard_task_runner.py:63} INFO - Started process 1356 to run task
[2025-01-07T13:02:22.965+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask random_dice
[2025-01-07T13:02:23.038+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2024-12-28T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:23.182+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2025-01-07T13:02:23.183+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:23.206+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-07T13:02:23.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:23.225+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2024-12-28T00:00:00+00:00, execution_date=20241228T000000, start_date=20250107T130222, end_date=20250107T130223
[2025-01-07T13:02:23.262+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-07T13:02:23.289+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:23.293+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
