[2025-01-07T13:02:11.043+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:11.108+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-30T00:00:00+00:00 [queued]>
[2025-01-07T13:02:11.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-30T00:00:00+00:00 [queued]>
[2025-01-07T13:02:11.133+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-01-07T13:02:11.171+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2024-12-30 00:00:00+00:00
[2025-01-07T13:02:11.196+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2024-12-30T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmpd4xyzzwa']
[2025-01-07T13:02:11.195+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1329) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:11.201+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask random_dice
[2025-01-07T13:02:11.203+0000] {standard_task_runner.py:63} INFO - Started process 1338 to run task
[2025-01-07T13:02:11.337+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2024-12-30T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:11.548+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T00:00:00+00:00'
[2025-01-07T13:02:11.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:11.587+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-07T13:02:11.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:11.614+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2024-12-30T00:00:00+00:00, execution_date=20241230T000000, start_date=20250107T130211, end_date=20250107T130211
[2025-01-07T13:02:11.680+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-07T13:02:11.715+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:11.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
