[2025-01-07T13:02:33.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T13:02:33.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2025-01-07T13:02:33.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.random_dice scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2025-01-07T13:02:33.924+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-01-07T13:02:33.948+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): random_dice> on 2024-12-29 00:00:00+00:00
[2025-01-07T13:02:33.955+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:02:33.957+0000] {standard_task_runner.py:63} INFO - Started process 1377 to run task
[2025-01-07T13:02:33.957+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'random_dice', 'scheduled__2024-12-29T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/skelet.py', '--cfg-path', '/tmp/tmpazigoqin']
[2025-01-07T13:02:33.958+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask random_dice
[2025-01-07T13:02:34.014+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.random_dice scheduled__2024-12-29T00:00:00+00:00 [running]> on host 006c1e931b5c
[2025-01-07T13:02:34.142+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='random_dice' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-29T00:00:00+00:00'
[2025-01-07T13:02:34.143+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T13:02:34.164+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-07T13:02:34.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T13:02:34.186+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=random_dice, run_id=scheduled__2024-12-29T00:00:00+00:00, execution_date=20241229T000000, start_date=20250107T130233, end_date=20250107T130234
[2025-01-07T13:02:34.252+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-07T13:02:34.279+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:02:34.284+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
